export const ROOT = 'ROOT';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

export const PROFILE = {
  LOADING: 'LOADING',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};

export const VEHICLE_LIST_LOADING = 'VEHICLE_LIST_LOADING';
export const VEHICLE_LIST_SUCCESS = 'VEHICLE_LIST_SUCCESS';
export const VEHICLE_LIST_ERROR = 'VEHICLE_LIST_ERROR';
